-- 70'ler Kafe & Mantı Evi — Masa / POS modülü
-- Bu modül aktif adisyonu tutar; ödeme tamamlandığında ilgili hesap ve ürün satırları silinir.
-- Geçmiş hesap, ciro veya muhasebe tablosu oluşturulmaz.

create table if not exists public.pos_settings (
  id integer primary key default 1 check (id=1),
  owner_user_id uuid references auth.users(id) on delete set null,
  updated_at timestamptz default now()
);
insert into public.pos_settings(id) values (1) on conflict (id) do nothing;

create table if not exists public.pos_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  email text,
  role text not null default 'personnel' check (role in ('admin','personnel')),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.pos_tables (
  id bigint generated by default as identity primary key,
  table_number integer not null unique check (table_number between 1 and 20),
  label text not null,
  created_at timestamptz default now()
);
insert into public.pos_tables(table_number,label)
select n, 'MASA '||n from generate_series(1,20) n
on conflict (table_number) do nothing;

create table if not exists public.pos_orders (
  id bigint generated by default as identity primary key,
  table_id bigint not null references public.pos_tables(id) on delete cascade,
  opened_at timestamptz not null default now(),
  opened_by uuid references auth.users(id) on delete set null
);

alter table public.pos_orders add column if not exists discount_percent numeric(5,2) not null default 0;
alter table public.pos_profiles add column if not exists email text;
create unique index if not exists pos_one_active_order_per_table on public.pos_orders(table_id);

create table if not exists public.pos_order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.pos_orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  unit_price numeric(10,2) not null check (unit_price >= 0),
  quantity integer not null default 1 check (quantity > 0),
  option_label text,
  note text,
  created_at timestamptz default now()
);
create index if not exists pos_order_items_order_idx on public.pos_order_items(order_id);

create or replace function public.get_my_pos_role()
returns text
language sql
security definer
set search_path=public,auth
as $$
  select case
    when exists(select 1 from public.pos_settings s where s.id=1 and s.owner_user_id=auth.uid()) then 'admin'
    else coalesce((select role from public.pos_profiles p where p.user_id=auth.uid()), 'none')
  end;
$$;

create or replace function public.bootstrap_pos_owner()
returns text
language plpgsql
security definer
set search_path=public,auth
as $$
begin
  if auth.uid() is null then return 'none'; end if;
  update public.pos_settings
     set owner_user_id=auth.uid(), updated_at=now()
   where id=1 and owner_user_id is null;
  return public.get_my_pos_role();
end;
$$;


create or replace function public.set_personnel_role(p_email text, p_display_name text default null)
returns text
language plpgsql
security definer
set search_path=public,auth
as $$
declare target_id uuid;
begin
  if public.get_my_pos_role() <> 'admin' then raise exception 'Yetkiniz yok.'; end if;
  select id into target_id from auth.users where lower(email)=lower(trim(p_email)) limit 1;
  if target_id is null then raise exception 'Bu e-posta ile Supabase Auth kullanıcısı bulunamadı. Önce kullanıcı hesabını oluşturun.'; end if;
  insert into public.pos_profiles(user_id,display_name,email,role,updated_at)
  values(target_id,nullif(trim(p_display_name),''),lower(trim(p_email)),'personnel',now())
  on conflict(user_id) do update set display_name=excluded.display_name, email=excluded.email, role='personnel', updated_at=now();
  return 'personnel';
end;
$$;

create or replace function public.remove_personnel_role(p_email text)
returns boolean
language plpgsql
security definer
set search_path=public,auth
as $$
declare target_id uuid;
begin
  if public.get_my_pos_role() <> 'admin' then raise exception 'Yetkiniz yok.'; end if;
  select id into target_id from auth.users where lower(email)=lower(trim(p_email)) limit 1;
  if target_id is null then return false; end if;
  delete from public.pos_profiles where user_id=target_id;
  return true;
end;
$$;

-- RLS: ürün/kategori okuma personelde de açık; değiştirme yalnızca admin.
alter table public.categories enable row level security;
alter table public.products enable row level security;
-- Yukarıdaki dinamik blok bazı PostgreSQL sürümlerinde policy adı çakışmasına karşı aşağıdaki güvenli blokla tamamlanır.
DO $$ declare r record; begin
  for r in select tablename, policyname from pg_policies where schemaname='public' and tablename in ('categories','products') loop
    execute format('drop policy if exists %I on public.%I',r.policyname,r.tablename);
  end loop;
end $$;
create policy categories_public_select on public.categories for select to anon,authenticated using (true);
create policy categories_admin_write on public.categories for all to authenticated using (public.get_my_pos_role()='admin') with check (public.get_my_pos_role()='admin');
create policy products_public_select on public.products for select to anon,authenticated using (true);
create policy products_admin_write on public.products for all to authenticated using (public.get_my_pos_role()='admin') with check (public.get_my_pos_role()='admin');

alter table public.pos_settings enable row level security;
alter table public.pos_profiles enable row level security;
alter table public.pos_tables enable row level security;
alter table public.pos_orders enable row level security;
alter table public.pos_order_items enable row level security;

DROP POLICY IF EXISTS pos_settings_owner_read ON public.pos_settings;
DROP POLICY IF EXISTS pos_profiles_admin_read ON public.pos_profiles;
DROP POLICY IF EXISTS pos_profiles_admin_write ON public.pos_profiles;
DROP POLICY IF EXISTS pos_tables_staff_all ON public.pos_tables;
DROP POLICY IF EXISTS pos_orders_staff_all ON public.pos_orders;
DROP POLICY IF EXISTS pos_items_staff_all ON public.pos_order_items;

create policy pos_settings_owner_read on public.pos_settings for select to authenticated using (owner_user_id=auth.uid());
create policy pos_profiles_admin_read on public.pos_profiles for select to authenticated using (public.get_my_pos_role()='admin');
create policy pos_profiles_admin_write on public.pos_profiles for all to authenticated using (public.get_my_pos_role()='admin') with check (public.get_my_pos_role()='admin');
create policy pos_tables_staff_all on public.pos_tables for all to authenticated using (public.get_my_pos_role() in ('admin','personnel')) with check (public.get_my_pos_role() in ('admin','personnel'));
create policy pos_orders_staff_all on public.pos_orders for all to authenticated using (public.get_my_pos_role() in ('admin','personnel')) with check (public.get_my_pos_role() in ('admin','personnel'));
create policy pos_items_staff_all on public.pos_order_items for all to authenticated using (public.get_my_pos_role() in ('admin','personnel')) with check (public.get_my_pos_role() in ('admin','personnel'));

grant select on public.pos_tables, public.pos_orders, public.pos_order_items to authenticated;
grant insert,update,delete on public.pos_tables, public.pos_orders, public.pos_order_items to authenticated;
grant usage,select on all sequences in schema public to authenticated;
grant execute on function public.get_my_pos_role() to authenticated;
grant execute on function public.bootstrap_pos_owner() to authenticated;
grant execute on function public.set_personnel_role(text,text) to authenticated;
grant execute on function public.remove_personnel_role(text) to authenticated;
